version: '3'

services:
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./accounts/src:/app/src:cached,ro
      - ./accounts/config:/app/config:cached,ro
      - ./accounts/.babelrc:/app/.babelrc:cached,ro
    environment:
      BLOCKCHAIN_HOST: http://ganache
      BLOCKCHAIN_PORT: 8545

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./api-gateway/src:/app/src:cached,ro
      - ./api-gateway/config:/app/config:cached,ro
      - ./api-gateway/.babelrc:/app/.babelrc:cached,ro
    ports:
      - "8001:80"
    environment:
      ACCOUNTS_HOST: http://accounts
      ACCOUNTS_PORT: 80
      ZKP_HOST: http://zkp
      ZKP_PORT: 80
      DATABASE_HOST: http://database
      DATABASE_PORT: 80
      OFFCHAIN_HOST: http://offchain
      OFFCHAIN_PORT: 80

  offchain:
    build:
      context: ./offchain
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./offchain/src:/app/src:cached,ro
      - ./offchain/build:/app/build:cached # Writeable for nodemon build
      - ./offchain/.babelrc:/app/.babelrc:cached,ro
      - ./offchain/__tests__:/app/__tests__:cached,ro
      - ./zkp-utils:/app/node_modules/zkp-utils:ro
      - ./account-utils:/app/src/account-utils:ro
      - ./offchain/config:/app/config:cached,ro
    environment:
      AUTHENTICATION_API_HOST: http://api-gateway
      AUTHENTICATION_API_PORT: 80
      BLOCKCHAIN_HOST: http://ganache
      BLOCKCHAIN_PORT: 8545

  zkp:
    build:
      context: ./zkp
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./zkp/src:/app/src:cached,ro
      - ./zkp/build:/app/build:delegated # Writeable for nodemon build
      - ./zkp/code:/app/code:cached # Writeable for ZoKrates build artifacts
      - ./zkp/.babelrc:/app/.babelrc:cached,ro
      - ./zkp-utils:/app/node_modules/zkp-utils:ro
      - ./account-utils:/app/src/account-utils:ro
      - ./zkp/__tests__:/app/__tests__:cached,ro
      - ./zkp/config:/app/config:cached,ro
      - /var/run/docker.sock:/var/run/docker.sock # Writeable for Docker control communication
    environment:
      BLOCKCHAIN_HOST: http://ganache
      BLOCKCHAIN_PORT: 8545
      ZKP_CODE_VOLUME: nightfall_zkp-code

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./ui/src:/app/src:cached,ro
      - ./ui/angular.json:/app/angular.json:cached,ro
      - ./ui/tsconfig.json:/app/tsconfig.json:cached,ro
    ports:
      - "8000:80"

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli --accounts=10 --defaultBalanceEther=1000
    ports:
      - "8545:8545"

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mongo
    volumes:
      - ./database/src:/app/src:cached,ro
      - ./database/.babelrc:/app/.babelrc:cached,ro
      - ./zkp-utils:/app/node_modules/zkp-utils:ro
      - ./database/config:/app/config:cached,ro
      - ./database/setup-mongo-acl-for-new-users.js:/app/setup-mongo-acl-for-new-users.js:cached,ro

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=nightfall
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d,ro
      - mongo-volume:/data/db # Writeable for database state

  truffle-offchain:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./offchain/contracts:/truffle/contracts:cached,ro
      - ./offchain/migrations/:/truffle/migrations:cached,ro
      - ./offchain/build/contracts/:/truffle/build/contracts:delegated # Writeable for Truffle compile
      - ./offchain/test/:/truffle/test:cached,ro
    depends_on:
      - ganache
    logging:
      options:
        max-size: 10m

  truffle-zkp:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./zkp/contracts/:/truffle/contracts:cached,ro
      - ./zkp/migrations/:/truffle/migrations:cached,ro
      - ./zkp/build/contracts/:/truffle/build/contracts:delegated # Writeable for Truffle compile
      - ./zkp/test/:/truffle/test:cached,ro
      - ./zkp/src/:/truffle/src:cached,ro
    depends_on:
      - ganache
    logging:
      options:
        max-size: 10m

volumes:
  mongo-volume: {}
  zkp-code:
    driver: local
    driver_opts:
      type: none
      device: $PWD/zkp/code/
      o: bind
